#!/bin/bash

#echo lösche \"Kategorie~*\"
#rm "Kategorie~*"
echo lösche \"Kategorie_Diskussion~*\"
rm "Kategorie_Diskussion~*"
echo lösche \"Bild~*\"
rm "Bild~*"
echo lösche \"Bild_Diskussion~*\"
rm "Bild_Diskussion~*"
echo lösche \"Portal~*\"
rm "Portal~*"
echo lösche \"Portal_Diskussion~*\"
rm "Portal_Diskussion~*"
echo lösche \"Diskussion~*\"
rm "Diskussion~*"
echo lösche \"Vorlage~*\"
rm "Vorlage~*"
echo lösche \"Vorlage_Diskussion~*\"
rm "Vorlage_Diskussion~*"
echo lösche \"Benutzer~*\"
rm "Benutzer~*"
echo lösche \"Benutzer_Diskussion~*\"
rm "Benutzer_Diskussion~*"
#echo lösche \"Spezial~*\"
#rm "Spezial~*"
#echo lösche \"Wikipedia~*\"
#rm "Wikipedia~*"
echo lösche \"Wikipedia_Diskussion~*\"
rm "Wikipedia_Diskussion~*"
echo lösche \"MediaWiki~*\"
rm "MediaWiki~*"
echo lösche \"MediaWiki_Diskussion~*\"
rm "MediaWiki_Diskussion~*"
echo lösche \"Hilfe~*\"
rm "Hilfe~*"
echo lösche \"Hilfe_Diskussion~*\"
rm "Hilfe_Diskussion~*"
echo lösche \"WP~*\"
rm "WP~*"
